apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms
spec:
  selector:
    matchLabels:
      app: ms
  replicas: 1
  template:
    metadata:
      labels:
        app: ms
    spec:
      containers:
      - name: ms
        image: ms
        imagePullPolicy: Never
