version: '3.7'
services:
  redis:
    container_name: redis-master
    image: 'redis'
    ports:
      - '6379:6379'
    networks:
      - generated-app-network
  frontend:
    container_name: frontend
    image: frontend
    build:
      context: ./frontend
      target: build-deps
      dockerfile: ./Dockerfile
    command: npm run start
    ports:
      - 3001:3000
    networks:
      - generated-app-network
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
  api-gateway:
    container_name: api-gateway
    image: api-gateway
    build:
      context: ./api_gateway
      target: development
      dockerfile: ./Dockerfile
    command: npm run start:dev
    ports:
      - 3000:3000
      - 9229:9229
    networks:
      - generated-app-network
    volumes:
      - ./api_gateway:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
  auth_ms:
    container_name: auth_ms
    image: auth_ms
    build:
      context: ./auth_ms
      target: development
      dockerfile: ./Dockerfile
    command: npm run start:dev
    networks:
      - generated-app-network
    volumes:
      - ./auth_ms:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
  ms:
    container_name: ms
    image: ms
    build:
      context: ./ms
      target: development
      dockerfile: ./Dockerfile
    command: npm run start:dev
    networks:
      - generated-app-network
    volumes:
      - ./ms:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

networks:
  generated-app-network:
